### ISSUE TITLE
[Bug] An issue with CoreUI modal and overlay

### ISSUE THREAD

**Issue by mialex** [Laravel-Backpack/theme-coreuiv4#57] opened 2024-09-29 08:33 UTC
# Bug report

### What I did

As far as I'm using CoreUI I want to use its features. One such features is Modal https://coreui.io/bootstrap/docs/components/modal/#content
Modal itself works, but the overlay is above the modal. 

![2024-09-29 11-31-25 Dashboard :: Backpack Admin Panel](https://github.com/user-attachments/assets/cad853da-8fc9-4bb2-8b53-f8b0be9bc992)

### How to reproduce

Just take an example from the Core UI page and embed it on any Laravel Backpack page as HTML block. I took a demo page.
- https://demo.backpackforlaravel.com/admin/dashboard

```html
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-coreui-toggle="modal" data-coreui-target="#exampleModal">
  Launch demo modal
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="btn-close" data-coreui-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-coreui-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>
```

**Comment by jcastroa87** [comment] 2024-09-29 14:02
Hello @mialex 

To replicate exactly the issue, where did you put this modal in HTML code? At the begging in body?, middle or end?

Cheers.

**Comment by mialex** [comment] 2024-09-29 19:02
@jcastroa87 before the first widget on the dashboard, but it doesn't matter where you put it.

**Comment by jcastroa87** [comment] 2024-09-30 18:41
I made a try on my side, using demo project and is working normal.

<img width="1859" alt="Screenshot 2024-09-30 at 3 40 10 PM" src="https://github.com/user-attachments/assets/09bece19-f749-466c-adea-d1abd3e8d320">

Can you give me more information how to reproduce error.

Is this a clean installation?

Cheers.

**Comment by jcastroa87** [comment] 2024-10-04 16:06
Due to not activity, I will close this issue, but please feel free to re-open or create a new one if needed.

Cheers.

**Closed by jcastroa87** 2024-10-04 16:06 UTC
